name: Update Streak Stats
on:
  schedule:
    - cron: "0 0 * * *" # Roda todo dia Ã  meia-noite
  workflow_dispatch: # Permite rodar manualmente para testar

jobs:
  update-streak:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate Streak Stats Image
        uses: DenverCoder1/github-readme-streak-stats@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user: rafaelxo
          mode: manual
      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update streak stats" || exit 0
          git push
